name: Test Project

on:
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    container:
      image: ghcr.io/itmo-asd-labin-2026/gcc-environment:15.2

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE="Debug"

      - name: Build Project
        run: cmake --build build
      
      - name: Run Tests
        working-directory: build
        run: ctest --output-on-failure